# Author Aleksandar Urosevic <urke.kg@gmail.com>
# Written for Sublime Text 3
# Convert Serbian Latin to Cyrillic script

import sublime, sublime_plugin

class LatCyrAllTranslitCommand(sublime_plugin.TextCommand):

	def run(self, edit):

		# get self view
		view = self.view

		# define region to replace (whole file)
		region = sublime.Region(0, view.size())
		content = view.substr(region)

		# double characters
		content = content.replace("lj", u"љ")
		content = content.replace("nj", u"њ")
		content = content.replace("dž", u"џ")
		content = content.replace("dj", u"ђ")
		content = content.replace("Lj", u"Љ")
		content = content.replace("Nj", u"Њ")
		content = content.replace("Dž", u"Џ")
		content = content.replace("Dj", u"Ђ")
		content = content.replace("LJ", u"Љ")
		content = content.replace("NJ", u"Њ")
		content = content.replace("DŽ", u"Џ")
		content = content.replace("DJ", u"Ђ")

		# lowercase characters
		content = content.replace("a", u"а")
		content = content.replace("b", u"б")
		content = content.replace("v", u"в")
		content = content.replace("g", u"г")
		content = content.replace("d", u"д")
		content = content.replace("đ", u"ђ")
		content = content.replace("e", u"е")
		content = content.replace("ž", u"ж")
		content = content.replace("z", u"з")
		content = content.replace("i", u"и")
		content = content.replace("j", u"ј")
		content = content.replace("k", u"к")
		content = content.replace("l", u"л")
		content = content.replace("m", u"м")
		content = content.replace("n", u"н")
		content = content.replace("o", u"о")
		content = content.replace("p", u"п")
		content = content.replace("r", u"р")
		content = content.replace("s", u"с")
		content = content.replace("t", u"т")
		content = content.replace("ć", u"ћ")
		content = content.replace("u", u"у")
		content = content.replace("f", u"ф")
		content = content.replace("h", u"х")
		content = content.replace("c", u"ц")
		content = content.replace("č", u"ч")
		content = content.replace("š", u"ш")

		# uppercase characters
		content = content.replace("A", u"А")
		content = content.replace("B", u"Б")
		content = content.replace("V", u"В")
		content = content.replace("G", u"Г")
		content = content.replace("D", u"Д")
		content = content.replace("Đ", u"Ђ")
		content = content.replace("E", u"Е")
		content = content.replace("Ž", u"Ж")
		content = content.replace("Z", u"З")
		content = content.replace("I", u"И")
		content = content.replace("J", u"Ј")
		content = content.replace("K", u"К")
		content = content.replace("L", u"Л")
		content = content.replace("M", u"М")
		content = content.replace("N", u"Н")
		content = content.replace("O", u"О")
		content = content.replace("P", u"П")
		content = content.replace("R", u"Р")
		content = content.replace("S", u"С")
		content = content.replace("T", u"Т")
		content = content.replace("Ć", u"Ћ")
		content = content.replace("U", u"У")
		content = content.replace("F", u"Ф")
		content = content.replace("H", u"Х")
		content = content.replace("C", u"Ц")
		content = content.replace("Č", u"Ч")
		content = content.replace("Š", u"Ш")

		# uppercase two-letter chars
		#content = content.replace(u"NjA", "NJA")
		#content = content.replace(u"NjE", "NJE")
		#content = content.replace(u"NjI", "NJI")
		#content = content.replace(u"NjO", "NJO")
		#content = content.replace(u"NjU", "NJU")
		#content = content.replace(u"ANj", "ANJ")
		#content = content.replace(u"ENj", "ENJ")
		#content = content.replace(u"INj", "INJ")
		#content = content.replace(u"ONj", "ONJ")
		#content = content.replace(u"UNj", "UNJ")

		# content = content.replace(u"LjA", "LJA")
		# content = content.replace(u"LjE", "LJE")
		# content = content.replace(u"LjI", "LJI")
		# content = content.replace(u"LjO", "LJO")
		# content = content.replace(u"LjU", "LJU")
		# content = content.replace(u"ALj", "ALJ")
		# content = content.replace(u"ELj", "ELJ")
		# content = content.replace(u"ILj", "ILJ")
		# content = content.replace(u"OLj", "OLJ")
		# content = content.replace(u"ULj", "ULJ")

		# content = content.replace(u"DžA", "DŽA")
		# content = content.replace(u"DžE", "DŽE")
		# content = content.replace(u"DžI", "DŽI")
		# content = content.replace(u"DžO", "DŽO")
		# content = content.replace(u"DžU", "DŽU")
		# content = content.replace(u"ADž", "ADŽ")
		# content = content.replace(u"EDž", "EDŽ")
		# content = content.replace(u"IDž", "IDŽ")
		# content = content.replace(u"ODž", "ODŽ")
		# content = content.replace(u"UDž", "UDŽ")

		# double characters Cyrillic
		content = content.replace("лј", u"љ")
		content = content.replace("нј", u"њ")
		content = content.replace("дж", u"џ")
		content = content.replace("дј", u"ђ")
		content = content.replace("Лј", u"Љ")
		content = content.replace("Нј", u"Њ")
		content = content.replace("Дж", u"Џ")
		content = content.replace("Дј", u"Ђ")
		content = content.replace("ЛЈ", u"Љ")
		content = content.replace("НЈ", u"Њ")
		content = content.replace("ДЖ", u"Џ")
		content = content.replace("ДЈ", u"Ђ")

		content = content.replace("ођ", u"одј")
		content = content.replace("родје", u"рође")
		content = content.replace("додје", u"дође")
		content = content.replace("пажИјив", u"пажљив")
		content = content.replace("акодје", u"акође")
		content = content.replace("одјеш", u"ођеш")
		content = content.replace("осподј", u"оспођ")
		content = content.replace("водја", u"вођа")
		content = content.replace("додја", u"дођа")
		content = content.replace("додји", u"дођи")
		content = content.replace("додју", u"дођу")
		content = content.replace("подји", u"пођи")
		content = content.replace("погодјен", u"погођен")
		content = content.replace("родјак", u"рођак")
		content = content.replace("родјен", u"рођен")

		content = content.replace("Ијуди", u"људи")
		content = content.replace("Ијуба", u"љуба")
		content = content.replace("Ијиљан", u"љиљан")
		content = content.replace("Додји", u"Дођи")
		content = content.replace("Додја", u"Дођа")
		content = content.replace("Додји", u"Дођи")
		content = content.replace("Додју", u"Дођу")
		content = content.replace("Подји", u"Пођи")
		content = content.replace("Погодјен", u"Погођен")
		content = content.replace("Родјак", u"Рођак")
		content = content.replace("Родјен", u"Рођен")

		# rimski brojevi - AU:20210619
		content = content.replace(" ВИИИ ", u" VIII ")
		content = content.replace(" ВИИ ", u" VII ")
		content = content.replace(" ВИ ", u" VI ")
		content = content.replace(" XВ ", u" XV ")
		content = content.replace(" XИX ", u" XIX ")
		content = content.replace(" XИИИ ", u" XIII ")
		content = content.replace(" XИИ ", u" XII ")
		content = content.replace(" XИ ", u" XI ")
		content = content.replace(" ИИИ ", u" III ")
		content = content.replace(" ИИ ", u" II ")
		content = content.replace(" ИВ ", u" IV ")
		content = content.replace(" ИX ", u" IX ")

		# HTML
		content = content.replace(u"и>", "i>")
		content = content.replace(u"у>", "u>")
		content = content.replace(u"б>", "b>")
		content = content.replace(u" </i>", "</i>")
		content = content.replace(u" </u>", "</u>")
		content = content.replace(u" </b>", "</b>")
		content = content.replace(u"<i> ", "<i>")
		content = content.replace(u"<u> ", "<u>")
		content = content.replace(u"<b> ", "<b>")
		content = content.replace(u"www.титлови.цом", "www.titlovi.com")
		
		# update content in view
		view.replace(edit, region, content)

		# close edit buffer
		view.end_edit(edit)

